### ISSUE TITLE
GuildChannel.clone

### ISSUE THREAD

**Issue by doEggi** [nyxx-discord/nyxx_extensions#38]
**Is your feature request related to a problem? Please describe.**
Apparently at the moment it is not possible to clone a channel with all its permissions.

**Describe the solution you'd like**
It would be nice to implement the .clone() function to GuildChannel 's

**Describe alternatives you've considered**
There are no alternatives known to me.

**Additional context**
https://discord.js.org/docs/packages/discord.js/14.15.3/BaseGuildTextChannel:Class#clone

**Comment by abitofevrything** [comment]
How does this method work? Does it create a new channel with the same properties? Does it create a builder for creating a new channel with the same properties?

**Comment by abitofevrything** [comment]
Instances of `GuildChannel` can only represent channels that _exist_. So this method either has to create a new channel itself, or return a builder. If it doesn't, I'm not really sure what the point is.

If you could give a clear explanation of what you expect this method to do, that would be helpful (discord.js' docs are particularily bad).

**Comment by doEggi** [comment]
The point would be to get every aspects of the channel (Name, Permissions aso) and create the exact same channel (with a new id of course; empty, so no messages).
In my special case I want to use it to clear a whole channel (duplicate, delete the old one, set the origin position to the new one).

**Comment by abitofevrything** [comment]
Would adding a `toBuilder()` method work for this? You could achieve the same by then creating a new channel with that builder.

**Comment by doEggi** [comment]
That would be perfect, with this you even could change specific values of the cloned channel.
